//namespace P01_BillsPaymentSystem.Initializer
//{
//    using System;
//    using System.Collections.Generic;
//    using System.Text;
//    using Data.Models;

//    public static class BankAccountsGenerator
//    {
//        public static BankAccount[] GetBankAccounts()
//        {
//            var bankAccounts = new[]
//            {
//                new BankAccount { Balance = 3100.98M, BankName = "Topicstorm", SwiftCode = "HTBX" },
//                new BankAccount { Balance = 636.19M, BankName = "Gabvine", SwiftCode = "STC" },
//                new BankAccount { Balance = 2698.92M, BankName = "Youspan", SwiftCode = "MDR" },
//                new BankAccount { Balance = 9377.56M, BankName = "Buzzbean", SwiftCode = "SXCP" },
//                new BankAccount { Balance = 850.67M, BankName = "Divape", SwiftCode = "SENEB" },
//                new BankAccount { Balance = 5477.48M, BankName = "Jaxnation", SwiftCode = "ARCI" },
//                new BankAccount { Balance = 2178.01M, BankName = "Jaxbean", SwiftCode = "QQXT" },
//                new BankAccount { Balance = 4006.26M, BankName = "Cogidoo", SwiftCode = "XIV" },
//                new BankAccount { Balance = 9269.02M, BankName = "Skilith", SwiftCode = "KELYA" },
//                new BankAccount { Balance = 6457.76M, BankName = "Miboo", SwiftCode = "QINC" },
//                new BankAccount { Balance = 6855.65M, BankName = "Camido", SwiftCode = "TEAR" },
//                new BankAccount { Balance = 6222.01M, BankName = "Topicshots", SwiftCode = "DRA" },
//                new BankAccount { Balance = 4387.46M, BankName = "Feedfire", SwiftCode = "EACQ" },
//                new BankAccount { Balance = 7108.17M, BankName = "Tanoodle", SwiftCode = "GBT" },
//                new BankAccount { Balance = 9086.65M, BankName = "Fadeo", SwiftCode = "WTM" },
//                new BankAccount { Balance = 1483.95M, BankName = "Thoughtsphere", SwiftCode = "OMC" },
//                new BankAccount { Balance = 5269.93M, BankName = "Quamba", SwiftCode = "JPS" },
//                new BankAccount { Balance = 9229.82M, BankName = "Gevee", SwiftCode = "HYGS" },
//                new BankAccount { Balance = 8147.26M, BankName = "Riffpath", SwiftCode = "LION" },
//                new BankAccount { Balance = 2548.73M, BankName = "Skyba", SwiftCode = "REVG" },
//                new BankAccount { Balance = 9970.17M, BankName = "Oyonder", SwiftCode = "ELS" },
//                new BankAccount { Balance = 3422.92M, BankName = "Thoughtbeat", SwiftCode = "USAK" },
//                new BankAccount { Balance = 5525.56M, BankName = "Avaveo", SwiftCode = "TPRE" },
//                new BankAccount { Balance = 4196.69M, BankName = "Linkbridge", SwiftCode = "WAFD" },
//                new BankAccount { Balance = 9709.08M, BankName = "Oodoo", SwiftCode = "MBT" },
//                new BankAccount { Balance = 2947.21M, BankName = "Tagpad", SwiftCode = "MIRN" },
//                new BankAccount { Balance = 5798.14M, BankName = "Yakidoo", SwiftCode = "HCOM" },
//                new BankAccount { Balance = 2722.4M, BankName = "Linkbridge", SwiftCode = "OFG^B" },
//                new BankAccount { Balance = 4443.32M, BankName = "Zoonder", SwiftCode = "XNCR" },
//                new BankAccount { Balance = 6420.61M, BankName = "Fivechat", SwiftCode = "JMT" },
//                new BankAccount { Balance = 5926.28M, BankName = "Plajo", SwiftCode = "SSL" },
//                new BankAccount { Balance = 7144.65M, BankName = "Muxo", SwiftCode = "NTP" },
//                new BankAccount { Balance = 6491.47M, BankName = "Yamia", SwiftCode = "ASML" },
//                new BankAccount { Balance = 7988.06M, BankName = "Myworks", SwiftCode = "GTHX" },
//                new BankAccount { Balance = 6108.7M, BankName = "Buzzbean", SwiftCode = "CBMG" },
//                new BankAccount { Balance = 5037.31M, BankName = "Mita", SwiftCode = "FSC" },
//                new BankAccount { Balance = 3721.7M, BankName = "Demivee", SwiftCode = "VCEL" },
//                new BankAccount { Balance = 3312.2M, BankName = "Reallinks", SwiftCode = "SCMP" },
//                new BankAccount { Balance = 7462.47M, BankName = "Dynazzy", SwiftCode = "STON" },
//                new BankAccount { Balance = 609.13M, BankName = "Aimbo", SwiftCode = "SCLN" },
//                new BankAccount { Balance = 7038.4M, BankName = "Cogibox", SwiftCode = "OKTA" },
//                new BankAccount { Balance = 1193.56M, BankName = "Linklinks", SwiftCode = "CP" },
//                new BankAccount { Balance = 4040.88M, BankName = "Yodo", SwiftCode = "OTEL" },
//                new BankAccount { Balance = 9948.11M, BankName = "Ooba", SwiftCode = "IDE" },
//                new BankAccount { Balance = 7251.22M, BankName = "Npath", SwiftCode = "GWRS" },
//                new BankAccount { Balance = 5554.85M, BankName = "Yakitri", SwiftCode = "FSS" },
//                new BankAccount { Balance = 8611.28M, BankName = "Realmix", SwiftCode = "MYSZ" },
//                new BankAccount { Balance = 2166.63M, BankName = "Meevee", SwiftCode = "MUX" },
//                new BankAccount { Balance = 7200.65M, BankName = "Trunyx", SwiftCode = "TMK^B" },
//                new BankAccount { Balance = 5008.28M, BankName = "Jabberbean", SwiftCode = "PAC" },
//                new BankAccount { Balance = 951.0M, BankName = "Flashdog", SwiftCode = "HCLP" },
//                new BankAccount { Balance = 5383.01M, BankName = "Buzzbean", SwiftCode = "OCUL" },
//                new BankAccount { Balance = 6250.3M, BankName = "Avamba", SwiftCode = "HUBG" },
//                new BankAccount { Balance = 3422.18M, BankName = "Rhyzio", SwiftCode = "BRCD" },
//                new BankAccount { Balance = 1482.22M, BankName = "Realmix", SwiftCode = "IIPR" },
//                new BankAccount { Balance = 7444.54M, BankName = "Jaxworks", SwiftCode = "ABBV" },
//                new BankAccount { Balance = 450.18M, BankName = "Kazio", SwiftCode = "STI" },
//                new BankAccount { Balance = 9487.16M, BankName = "Trudeo", SwiftCode = "VIVE" },
//                new BankAccount { Balance = 3194.79M, BankName = "Zoomlounge", SwiftCode = "OXLCO" },
//                new BankAccount { Balance = 5270.75M, BankName = "Minyx", SwiftCode = "KNX" },
//                new BankAccount { Balance = 3172.92M, BankName = "Skiba", SwiftCode = "TNP^E" },
//                new BankAccount { Balance = 7293.08M, BankName = "Camimbo", SwiftCode = "CATY" },
//                new BankAccount { Balance = 8194.29M, BankName = "Vimbo", SwiftCode = "BAC.WS.A" },
//                new BankAccount { Balance = 8480.84M, BankName = "Livetube", SwiftCode = "CTWS" },
//                new BankAccount { Balance = 8379.87M, BankName = "Quinu", SwiftCode = "EVA" },
//                new BankAccount { Balance = 301.06M, BankName = "Demizz", SwiftCode = "GOGL" },
//                new BankAccount { Balance = 3876.01M, BankName = "Meeveo", SwiftCode = "VTWG" },
//                new BankAccount { Balance = 1323.0M, BankName = "Thoughtstorm", SwiftCode = "ALLT" },
//                new BankAccount { Balance = 724.28M, BankName = "Abata", SwiftCode = "HURC" },
//                new BankAccount { Balance = 9527.67M, BankName = "Linktype", SwiftCode = "DLHC" },
//                new BankAccount { Balance = 4340.58M, BankName = "Feednation", SwiftCode = "PCF" },
//                new BankAccount { Balance = 3892.46M, BankName = "Kwinu", SwiftCode = "GE" },
//                new BankAccount { Balance = 3317.49M, BankName = "Muxo", SwiftCode = "IGT" },
//                new BankAccount { Balance = 3222.33M, BankName = "Demivee", SwiftCode = "ISBC" },
//                new BankAccount { Balance = 6288.09M, BankName = "Blogspan", SwiftCode = "CHT" },
//                new BankAccount { Balance = 8564.7M, BankName = "Jabbertype", SwiftCode = "ICB" },
//                new BankAccount { Balance = 1669.24M, BankName = "Yombu", SwiftCode = "SRC" },
//                new BankAccount { Balance = 3151.4M, BankName = "Flipopia", SwiftCode = "AGM^A" },
//                new BankAccount { Balance = 9075.47M, BankName = "Aimbu", SwiftCode = "FN" },
//                new BankAccount { Balance = 7729.03M, BankName = "Eidel", SwiftCode = "HYLS" },
//                new BankAccount { Balance = 4474.11M, BankName = "Tazzy", SwiftCode = "TAYD" },
//                new BankAccount { Balance = 5674.14M, BankName = "Tagopia", SwiftCode = "MIRN" },
//                new BankAccount { Balance = 919.46M, BankName = "Wordpedia", SwiftCode = "DSU" },
//                new BankAccount { Balance = 1047.1M, BankName = "Skalith", SwiftCode = "FARO" },
//                new BankAccount { Balance = 6099.46M, BankName = "Jetpulse", SwiftCode = "QUAD" },
//                new BankAccount { Balance = 6844.14M, BankName = "Oyonder", SwiftCode = "MGRC" },
//                new BankAccount { Balance = 4166.7M, BankName = "Yadel", SwiftCode = "BLD" },
//                new BankAccount { Balance = 9185.48M, BankName = "Twitterwire", SwiftCode = "SFL" },
//                new BankAccount { Balance = 4162.49M, BankName = "Tagchat", SwiftCode = "SNSR" },
//                new BankAccount { Balance = 5839.26M, BankName = "Kamba", SwiftCode = "HCCI" },
//                new BankAccount { Balance = 3290.28M, BankName = "Livetube", SwiftCode = "QTNA" },
//                new BankAccount { Balance = 685.31M, BankName = "Fliptune", SwiftCode = "ARCH" },
//                new BankAccount { Balance = 8156.44M, BankName = "Tavu", SwiftCode = "PSA^W" },
//                new BankAccount { Balance = 6938.82M, BankName = "Skalith", SwiftCode = "KAACW" },
//                new BankAccount { Balance = 8419.61M, BankName = "Realbuzz", SwiftCode = "NNY" },
//                new BankAccount { Balance = 2830.57M, BankName = "Oloo", SwiftCode = "OACQW" },
//                new BankAccount { Balance = 7325.45M, BankName = "Skinix", SwiftCode = "RCMT" },
//                new BankAccount { Balance = 198.04M, BankName = "Zoonder", SwiftCode = "PFIS" },
//                new BankAccount { Balance = 7240.51M, BankName = "Twiyo", SwiftCode = "KELYB" },
//                new BankAccount { Balance = 7346.39M, BankName = "Plajo", SwiftCode = "BCPC" }
//            };

//            return bankAccounts;
//        }
//    }
//}