namespace P01_BillsPaymentSystem.Initializer
{
    using Data.Models;

    public static class UsersGenerator
    {
        public static User[] GetUsers()
        {
            var users = new[]
            {
                new User{ FirstName = "Marthe", LastName = "Mason", Email = "mmason0@microsoft.com", Password = "vMTn1Oo5u" },
                new User{ FirstName = "Shayne", LastName = "Glynn", Email = "sglynn1@mapquest.com", Password = "c01BsaVDsPzt" },
                new User{ FirstName = "Cicely", LastName = "Cheeney", Email = "ccheeney2@timesonline.co.uk", Password = "DY2DX9Q" },
                new User{ FirstName = "Kellen", LastName = "Titman", Email = "ktitman3@unicef.org", Password = "flyxNSxHWyu" },
                new User{ FirstName = "Beverly", LastName = "Artrick", Email = "bartrick4@bbc.co.uk", Password = "NLpsBZIWWoy" },
                new User{ FirstName = "Berna", LastName = "Hirtzmann", Email = "bhirtzmann5@tmall.com", Password = "XIFN3F" },
                new User{ FirstName = "Ilse", LastName = "Rameaux", Email = "irameaux6@globo.com", Password = "OjQ9zE4XJ4" },
                new User{ FirstName = "Tess", LastName = "Bawcock", Email = "tbawcock7@upenn.edu", Password = "i18pUEu" },
                new User{ FirstName = "Lauritz", LastName = "Forseith", Email = "lforseith8@aboutads.info", Password = "ecVdON" },
                new User{ FirstName = "Roze", LastName = "Otter", Email = "rotter9@hc360.com", Password = "jQxnJA4S" },
                new User{ FirstName = "Freeman", LastName = "Consterdine", Email = "fconsterdinea@slideshare.net", Password = "73e1YqGcxd" },
                new User{ FirstName = "Darius", LastName = "Mouatt", Email = "dmouattb@oracle.com", Password = "WjxPUQBsOvE7" },
                new User{ FirstName = "Michell", LastName = "Lovemore", Email = "mlovemorec@ucoz.ru", Password = "2Jp7RKkPeMpH" },
                new User{ FirstName = "Godfry", LastName = "Jeens", Email = "gjeensd@wix.com", Password = "m6lIpHoun8AO" },
                new User{ FirstName = "Krystal", LastName = "Lucian", Email = "kluciane@disqus.com", Password = "TqV1ybwl6" },
                new User{ FirstName = "Arnoldo", LastName = "Geindre", Email = "ageindref@instagram.com", Password = "DN7NaBuCwhZ3" },
                new User{ FirstName = "Merola", LastName = "Wimsett", Email = "mwimsettg@dedecms.com", Password = "S6OxycnKZvG" },
                new User{ FirstName = "Tedra", LastName = "Medland", Email = "tmedlandh@timesonline.co.uk", Password = "BK4Yw9lRKnD7" },
                new User{ FirstName = "Johnathan", LastName = "Rosenau", Email = "jrosenaui@slideshare.net", Password = "uU4sEb9u0" },
                new User{ FirstName = "Kessia", LastName = "Feragh", Email = "kferaghj@xrea.com", Password = "IUPnqblvu2y" },
                new User{ FirstName = "Currie", LastName = "Margiotta", Email = "cmargiottak@boston.com", Password = "Qk6WePi" },
                new User{ FirstName = "Everett", LastName = "Milsted", Email = "emilstedl@bloglovin.com", Password = "qRwQLr" },
                new User{ FirstName = "Jeanine", LastName = "Well", Email = "jwellm@chron.com", Password = "Ov0STIX" },
                new User{ FirstName = "Dorthy", LastName = "Squibbs", Email = "dsquibbsn@wix.com", Password = "2EJOSMSu" },
                new User{ FirstName = "Flint", LastName = "Snaddin", Email = "fsnaddino@topsy.com", Password = "qEphxzQoG" },
                new User{ FirstName = "Mildred", LastName = "Riley", Email = "mrileyp@fema.gov", Password = "9guKtYZnZV" },
                new User{ FirstName = "Ron", LastName = "Berdale", Email = "rberdaleq@gizmodo.com", Password = "HETGJb1hzG" },
                new User{ FirstName = "Kipp", LastName = "Pahler", Email = "kpahlerr@techcrunch.com", Password = "FRJ3R6XSUyVp" },
                new User{ FirstName = "Madlin", LastName = "Francescuccio", Email = "mfrancescuccios@chronoengine.com", Password = "oglxJKDkf" },
                new User{ FirstName = "Lamont", LastName = "Belitz", Email = "lbelitzt@webeden.co.uk", Password = "lXVSavx9iq" },
                new User{ FirstName = "Leo", LastName = "Baroche", Email = "lbarocheu@canalblog.com", Password = "ALYhYCUzp" },
                new User{ FirstName = "Anton", LastName = "Macauley", Email = "amacauleyv@sogou.com", Password = "ZdR4xbz" },
                new User{ FirstName = "Marne", LastName = "Durdan", Email = "mdurdanw@mapy.cz", Password = "H5kzObvh8Tla" },
                new User{ FirstName = "Devonne", LastName = "Jenkyn", Email = "djenkynx@dyndns.org", Password = "Za28WrldMIa" },
                new User{ FirstName = "Morly", LastName = "Gianni", Email = "mgianniy@vinaora.com", Password = "HhVGHRRs" },
                new User{ FirstName = "Prinz", LastName = "Luesley", Email = "pluesleyz@themeforest.net", Password = "oWOznkbx" },
                new User{ FirstName = "Maxie", LastName = "D'Adda", Email = "mdadda10@loc.gov", Password = "MhlTAP" },
                new User{ FirstName = "Kerri", LastName = "Caslake", Email = "kcaslake11@scribd.com", Password = "E1BAqtYLMts" },
                new User{ FirstName = "Shaylynn", LastName = "Gorges", Email = "sgorges12@gnu.org", Password = "ZxL6NGVID5Qa" },
                new User{ FirstName = "Tito", LastName = "McFaell", Email = "tmcfaell13@indiatimes.com", Password = "GgKoMjM5PPdb" },
                new User{ FirstName = "Alexandra", LastName = "Leathart", Email = "aleathart14@weibo.com", Password = "4jgKb9FWO" },
                new User{ FirstName = "Marketa", LastName = "Stanworth", Email = "mstanworth15@reverbnation.com", Password = "EsqK7AE" },
                new User{ FirstName = "Petronella", LastName = "Dyde", Email = "pdyde16@nba.com", Password = "Qqdm6ZFtw8zd" },
                new User{ FirstName = "Toinette", LastName = "Aspin", Email = "taspin17@photobucket.com", Password = "DdkaNXLIA" },
                new User{ FirstName = "Rhoda", LastName = "Brunnstein", Email = "rbrunnstein18@imageshack.us", Password = "Ais7xrr1a6T4" },
                new User{ FirstName = "Bobby", LastName = "Meeking", Email = "bmeeking19@taobao.com", Password = "sefyYlu" },
                new User{ FirstName = "Sophie", LastName = "Iwanczyk", Email = "siwanczyk1a@tiny.cc", Password = "9Vag6wpp" },
                new User{ FirstName = "Chiarra", LastName = "Antonoczyk", Email = "cantonoczyk1b@marketwatch.com", Password = "ymffKpEt" },
                new User{ FirstName = "Linnie", LastName = "Cutchie", Email = "lcutchie1c@merriam-webster.com", Password = "NR03BCwFwZo" },
                new User{ FirstName = "Zeb", LastName = "MacAlroy", Email = "zmacalroy1d@imageshack.us", Password = "GKLTce" },
                new User{ FirstName = "Byrann", LastName = "Turfus", Email = "bturfus1e@loc.gov", Password = "PoCugcB" },
                new User{ FirstName = "Leisha", LastName = "Tester", Email = "ltester1f@g.co", Password = "fC89JSu" },
                new User{ FirstName = "Hilarius", LastName = "Ault", Email = "hault1g@chicagotribune.com", Password = "14Up9L2X" },
                new User{ FirstName = "Dani", LastName = "Pudge", Email = "dpudge1h@sun.com", Password = "vpeLpN" },
                new User{ FirstName = "Melodie", LastName = "Grubb", Email = "mgrubb1i@usgs.gov", Password = "6sMUPk6" },
                new User{ FirstName = "Arney", LastName = "Osmint", Email = "aosmint1j@nba.com", Password = "88EHGdZS" },
                new User{ FirstName = "Francine", LastName = "MacIlhagga", Email = "fmacilhagga1k@nymag.com", Password = "05h1eFN" },
                new User{ FirstName = "Cherilyn", LastName = "Newberry", Email = "cnewberry1l@disqus.com", Password = "tChL0eMC" },
                new User{ FirstName = "Odey", LastName = "Garrattley", Email = "ogarrattley1m@yahoo.co.jp", Password = "NTgaJmM" },
                new User{ FirstName = "Jordon", LastName = "Tooley", Email = "jtooley1n@ebay.com", Password = "4UHSjmUcq" },
                new User{ FirstName = "Storm", LastName = "Carl", Email = "scarl1o@ca.gov", Password = "eLhwhRKUZJb2" },
                new User{ FirstName = "Brigitta", LastName = "Torrecilla", Email = "btorrecilla1p@shinystat.com", Password = "rwtWd3K" },
                new User{ FirstName = "Slade", LastName = "Lippard", Email = "slippard1q@dagondesign.com", Password = "ZGMSPtNd" },
                new User{ FirstName = "Retha", LastName = "Rogan", Email = "rrogan1r@fc2.com", Password = "77HSKeX3t8f" },
                new User{ FirstName = "Karry", LastName = "Pieracci", Email = "kpieracci1s@scribd.com", Password = "OFbABSuC" },
                new User{ FirstName = "Meagan", LastName = "Dunmuir", Email = "mdunmuir1t@boston.com", Password = "Qt0biKpx6" },
                new User{ FirstName = "Prentice", LastName = "Geaney", Email = "pgeaney1u@virginia.edu", Password = "d7fFzi4Byp" },
                new User{ FirstName = "Marianna", LastName = "Coping", Email = "mcoping1v@hugedomains.com", Password = "EbY5U2t21d" },
                new User{ FirstName = "Amalea", LastName = "Aimson", Email = "aaimson1w@nba.com", Password = "nkenfSUtE" },
                new User{ FirstName = "Meredith", LastName = "Kleinstub", Email = "mkleinstub1x@shinystat.com", Password = "issWXE6mwngj" },
                new User{ FirstName = "Gaynor", LastName = "Aizlewood", Email = "gaizlewood1y@stanford.edu", Password = "KxFuCT" },
                new User{ FirstName = "Ailyn", LastName = "Greenstead", Email = "agreenstead1z@angelfire.com", Password = "0Uq7qC0idd1" },
                new User{ FirstName = "Marshall", LastName = "Trobey", Email = "mtrobey20@cam.ac.uk", Password = "H0d2IV2yH" },
                new User{ FirstName = "Markus", LastName = "Ballaam", Email = "mballaam21@vinaora.com", Password = "QDKZmwNHFJ" },
                new User{ FirstName = "Gypsy", LastName = "Lapidus", Email = "glapidus22@dmoz.org", Password = "lDxsw3EdaDR" },
                new User{ FirstName = "Effie", LastName = "Di Francecshi", Email = "edifrancecshi23@edublogs.org", Password = "OeL7tp" },
                new User{ FirstName = "Damara", LastName = "Manis", Email = "dmanis24@flickr.com", Password = "kGqG7DXE" },
                new User{ FirstName = "Charisse", LastName = "Goldes", Email = "cgoldes25@live.com", Password = "1ZLYfLRn7F" },
                new User{ FirstName = "Othello", LastName = "Alcalde", Email = "oalcalde26@yellowpages.com", Password = "AcFrJQHN" },
                new User{ FirstName = "Norris", LastName = "Parramore", Email = "nparramore27@lycos.com", Password = "2EcINoA4r" },
                new User{ FirstName = "Mandi", LastName = "Waldie", Email = "mwaldie28@digg.com", Password = "C4UGA1" },
                new User{ FirstName = "Ofilia", LastName = "Horche", Email = "ohorche29@blogspot.com", Password = "limvXFzy" },
                new User{ FirstName = "Aldwin", LastName = "Sapsford", Email = "asapsford2a@parallels.com", Password = "9LXIut9bP5L" },
                new User{ FirstName = "Raquela", LastName = "Hallybone", Email = "rhallybone2b@comsenz.com", Password = "t3FCQdqY" },
                new User{ FirstName = "Larry", LastName = "Jewkes", Email = "ljewkes2c@dot.gov", Password = "VP0fVfXOnOW" },
                new User{ FirstName = "Birdie", LastName = "Rossey", Email = "brossey2d@npr.org", Password = "Ptk4JpLGVG" },
                new User{ FirstName = "Conney", LastName = "Calbrathe", Email = "ccalbrathe2e@topsy.com", Password = "NHANvrMw" },
                new User{ FirstName = "Arvin", LastName = "Hamberston", Email = "ahamberston2f@answers.com", Password = "mApRJZJqHo" },
                new User{ FirstName = "Benetta", LastName = "Guilayn", Email = "bguilayn2g@simplemachines.org", Password = "Put67qNT" },
                new User{ FirstName = "Walden", LastName = "Sellstrom", Email = "wsellstrom2h@unesco.org", Password = "TMidptxgi" },
                new User{ FirstName = "Isak", LastName = "Haydn", Email = "ihaydn2i@is.gd", Password = "P4CGN3qP" },
                new User{ FirstName = "Debora", LastName = "Lornsen", Email = "dlornsen2j@scientificamerican.com", Password = "BOxIZG" },
                new User{ FirstName = "Harlen", LastName = "Feedome", Email = "hfeedome2k@tripod.com", Password = "dXYsjmSIZc" },
                new User{ FirstName = "Codi", LastName = "Eccleston", Email = "ceccleston2l@bandcamp.com", Password = "IkaHaOkNyIF1" },
                new User{ FirstName = "Chrystel", LastName = "Merrikin", Email = "cmerrikin2m@dion.ne.jp", Password = "ZexLnu9ew" },
                new User{ FirstName = "Stanton", LastName = "Menier", Email = "smenier2n@blinklist.com", Password = "1VTU6H" },
                new User{ FirstName = "Suzanna", LastName = "Mullinger", Email = "smullinger2o@ifeng.com", Password = "XSmCGVbg" },
                new User{ FirstName = "Jacobo", LastName = "McKinty", Email = "jmckinty2p@etsy.com", Password = "m7EeObRaa" },
                new User{ FirstName = "Moshe", LastName = "Sollon", Email = "msollon2q@ovh.net", Password = "bCuu0L24" },
                new User{ FirstName = "Correy", LastName = "Kline", Email = "ckline2r@cnet.com", Password = "fesOelH0uNA" }
            };

            return users;
        }
    }
}