// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P012_BillsPaymentSystemTPH.Data;

namespace P012_BillsPaymentSystemTPH.Data.Migrations
{
    [DbContext(typeof(BillsPaymentSystemTphContext))]
    [Migration("20190128154655_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("P012_BillsPaymentSystemTPH.Models.PaymentMethods.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentsMethods");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PaymentMethod");
                });

            modelBuilder.Entity("P012_BillsPaymentSystemTPH.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P012_BillsPaymentSystemTPH.Models.PaymentMethods.BankAccount", b =>
                {
                    b.HasBaseType("P012_BillsPaymentSystemTPH.Models.PaymentMethods.PaymentMethod");

                    b.Property<string>("BankName");

                    b.Property<string>("Swift");

                    b.HasDiscriminator().HasValue("BankAccount");
                });

            modelBuilder.Entity("P012_BillsPaymentSystemTPH.Models.PaymentMethods.CreditCard", b =>
                {
                    b.HasBaseType("P012_BillsPaymentSystemTPH.Models.PaymentMethods.PaymentMethod");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<int>("Type");

                    b.HasDiscriminator().HasValue("CreditCard");
                });

            modelBuilder.Entity("P012_BillsPaymentSystemTPH.Models.PaymentMethods.PaymentMethod", b =>
                {
                    b.HasOne("P012_BillsPaymentSystemTPH.Models.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
